#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *
from heapq import heapify, heappush, heappop
from functools import reduce

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    content = read_lines(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    banks = []
    for line in content:
        bank = [int(char) for char in line]
        banks.append(bank)
    return banks

#===============================================================================
def process_data(data):
    """Process data as needed"""
    result = 0
    for bank in data:
        n = len(bank)
        k = n-12
        heap = [(-bank[i],i) for i in range(0,k)]
        heapify(heap)
        output = [(0,-1)] * 12
        l = -1
        for i in range(12):
            heappush(heap, (-bank[k],k))
            item = heappop(heap)
            while item[1] < output[l][1]:
                item = heappop(heap)
            k += 1
            l += 1
            output[l] = item
        output = reduce(lambda acc,x: 10*acc-x[0], output, 0)
        result += output
        #print(output)
    return result

#===============================================================================
if __name__ == "__main__":
    main()

#1111922291111
