#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    content = read_lines(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    return [[c == '@' for c in line] for line in content]

#===============================================================================
def process_data(data):
    """Process data as needed"""
    n = len(data)
    m = len(data[0])
    count = 0
    adj = 0
    col = [0,0,0]
    # Center
    for i in range(1,n-1):
        col[0] = data[i-1][0] + data[i][0] + data[i+1][0]
        col[1] = data[i-1][1] + data[i][1] + data[i+1][1]
        k = 2
        adj = col[0] + col[1]

        for j in range(1,m-1):
            col[k] = data[i-1][j+1] + data[i][j+1] + data[i+1][j+1]
            adj += col[k]
            count += (adj <= 4) and data[i][j]
            k = k+1 if k<2 else 0
            adj -= col[k]

    # Corners
    count += data[0][0] + data[-1][-1] + data[ 0][-1] + data[-1][ 0]
    adj1 = data[ 0][ 0] + data[ 0][ 1] + data[ 1][ 0] + data[ 1][ 1]
    adj2 = data[-1][ 0] + data[-1][ 1] + data[-2][ 0] + data[-2][ 1]
    adj3 = data[ 0][ 0] + data[ 1][ 0] + data[ 0][ 1] + data[ 1][ 1]
    adj4 = data[ 0][-1] + data[ 1][-1] + data[ 0][-2] + data[ 1][-2]

    # top and bottom edges
    for j in range(1,m-1):
        adj1  += data[ 0][j+1] + data[ 1][j+1]
        adj2  += data[-1][j+1] + data[-2][j+1]
        count += data[ 0][ j ] and adj1 <= 4
        count += data[-1][ j ] and adj2 <= 4
        adj1  -= data[ 0][j-1] + data[ 1][j-1]
        adj2  -= data[-1][j-1] + data[-2][j-1]

    # left and right edges
    for i in range(1,n-1):
        adj3  += data[i+1][ 0] + data[i+1][ 1]
        adj4  += data[i+1][-1] + data[i+1][-2]
        count += data[ i ][ 0] and adj3 <= 4
        count += data[ i ][-1] and adj4 <= 4
        adj3  -= data[i-1][ 0] + data[i-1][ 1]
        adj4  -= data[i-1][-1] + data[i-1][-2]

    return count

#===============================================================================
if __name__ == "__main__":
    main()
