#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    content = read_lines(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    return [[0] + [int(c == '@') for c in line] + [0] for line in content]

#===============================================================================
def process_data(data):
    """Process data as needed"""
    n = len(data) + 2
    m = len(data[0])
    data = [[0]*m] + data + [[0]*m]
    next = [[0 for j in range(m)] for i in range(n)]
    n -= 1
    m -= 1
    adj = 0
    col = [0,0,0]
    total = 0
    count = 1
    while count > 0:
        count = 0
        for i in range(1,n):
            col[0] = data[i-1][0] + data[i][0] + data[i+1][0]
            col[1] = data[i-1][1] + data[i][1] + data[i+1][1]
            k = 2
            adj = col[0] + col[1]
            for j in range(1,m):
                col[k] = data[i-1][j+1] + data[i][j+1] + data[i+1][j+1]
                adj += col[k]
                count += (adj <= 4) and data[i][j]
                next[i][j] = int((adj >  4) and data[i][j])
                #print('.' if data[i][j] == 0 else '@' if (adj > 4) else 'x', end='')
                k = k+1 if k<2 else 0
                adj -= col[k]
            #print()

        total += count
        (data,next) = (next,data)
        #print("Removed",count,"roll of paper.\n")

    return total

#===============================================================================
if __name__ == "__main__":
    main()
