#!/usr/bin/python
from sys import argv

def main():

    if len(argv) != 2:
        print("Invalid # of arguments")
        return

    data = []
    dim, lines, start = preprocess(argv[1])

    process_data(dim, lines, start)

    for line in lines:
        data.append(process_line(line))

convert = {
    'F':'p',
    'J':'d',
    'L':'b',
    '7':'q',
    '.':'.',
    '-':'-',
    '|':'|',
}

def preprocess(file):
    height = 0
    lines = []
    start = None
    with open(argv[1]) as file:
        content = file.read().split('\n')
    width = len(content[0])
    column = range(width)
    for line in content:
        line = list(line.strip())
        if line:
            for x in column:
                if line[x] == 'S':
                    start = (height, x)
                else: line[x] = convert[line[x]]
            lines.append(line)
            height += 1
    return (height, width), lines, start

def process_line(line):
    out = ""
    for char in line:
        out += '.' if char in convert.values() else char
    print(out)

tile = {
    'N': { 'p':{'x':1,'y':0,'d':'E'}, 'q':{'x':-1,'y': 0,'d':'W'}, '|':{'x': 0,'y':-1,'d':'N'} },
    'S': { 'b':{'x':1,'y':0,'d':'E'}, 'd':{'x':-1,'y': 0,'d':'W'}, '|':{'x': 0,'y': 1,'d':'S'} },
    'E': { 'q':{'x':0,'y':1,'d':'S'}, 'd':{'x': 0,'y':-1,'d':'N'}, '-':{'x': 1,'y': 0,'d':'E'} },
    'W': { 'p':{'x':0,'y':1,'d':'S'}, 'b':{'x': 0,'y':-1,'d':'N'}, '-':{'x':-1,'y': 0,'d':'W'} },
}

def process_data(dim, chart, start):
    h = dim[0]
    w = dim[1]
    y = [start[0], 0, 0]
    x = [start[1], 0, 0]
    pipe = ['S', '', '']
    d  = ['', '', '']
    chart[y[0]][x[0]] = '0'
    next = 1
    feature = chart[y[0]][x[0]-1]
    if x[0] > 0 and feature in tile['W'].keys():
        pipe[next] = feature
        x[next] = x[0]-1
        y[next] = y[0]
        d[next] = 'W'
        chart[y[next]][x[next]] = '1'
        next += 1
    feature = chart[y[0]][x[0]+1]
    if x[0] < w and feature in tile['E'].keys():
        pipe[next] = feature
        x[next] = x[0]+1
        y[next] = y[0]
        d[next] = 'E'
        chart[y[next]][x[next]] = '1'
        next += 1
    feature = chart[y[0]-1][x[0]]
    if y[0] > 0 and feature in tile['N'].keys():
        pipe[next] = feature
        x[next] = x[0]
        y[next] = y[0]-1
        d[next] = 'N'
        chart[y[next]][x[next]] = '1'
        next += 1
    feature = chart[y[0]+1][x[0]]
    if y[0] < h and feature in tile['S'].keys():
        pipe[next] = feature
        x[next] = x[0]
        y[next] = y[0]+1
        d[next] = 'S'
        chart[y[next]][x[next]] = '1'
        next += 1
    step = 1
    print(step, d[1], d[2])
    try:
        while x[1] != x[2] or y[1] != y[2]:
            step += 1
            for i in (1,2):
                x[i] += tile[d[i]][pipe[i]]['x']
                y[i] += tile[d[i]][pipe[i]]['y']
                d[i]  = tile[d[i]][pipe[i]]['d']
                pipe[i] = chart[y[i]][x[i]]
                if step < 10:
                    symbol = str(step)
                else: symbol = chr(ord('A') + ((step - 10) % 26))
                chart[y[i]][x[i]] = symbol
            print(step, d[1], d[2])
        print("It will take",step, "steps!")
    except Exception as e:
        print('[!]',repr(e))
        print('[!] x=',x,'  y=',y,'  d=',d,'  p=',pipe,sep='')
        for line in chart:
            print("\t", ''.join(line))
        exit()
        


if __name__ == "__main__":
    main()
