#!/usr/bin/python
from sys import argv

schematic = []
symbol = []

for arg in argv[1:]:
    schematic.append(arg)
    symbol.append([])
    for char in arg:
        symbol[-1].append(char != '.' and not char.isdigit())

def is_part(x1, x2, y1, y2, symbol):
    for y in range(y1, y2+1):
        for x in range(x1, x2+1):
            if symbol[y][x]:
                return True
    return False

width = len(schematic[0])
height = len(schematic)
total = 0
for y in range(height):
    part = 0
    start = -1
    for x in range(width):
        item = schematic[y][x]
        if item.isdigit():
            part *= 10
            part += ord(item) - 0x30
            if start < 0:
                start = max(0, x-1)
        else:
            if start >= 0:
                if is_part(start, x, max(0, y-1), min(height-1, y+1), symbol):
                    total += part
                else: print(y,":",part,"is not a part")
            start = -1
            part = 0
    if start >= 0:
        if is_part(start, width-1, max(0, y-1), min(height-1, y+1), symbol):
            total += part
        else: print(y,":",part,"is not a part")
print("sum:", total)

