#!/usr/bin/python
"""Advent of Code Solution"""

from sys import argv

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    if len(argv) != 2:
        print("Invalid # of arguments")
        return
    content = preprocess(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def preprocess(filename):
    """Extract lines from file"""
    content = [[]]
    with open(filename,encoding="utf8") as file:
        lines = file.read().split('\n')
    for line in lines:
        if line:
            content[-1].append(line)
        else:
            content.append([])
    return content[:-1]

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    equations = []
    for system in content:
        eq1 = system[0].split()
        eq2 = system[1].split()
        eq3 = system[2].split()
        a1 = int(eq1[2][2:-1])
        a2 = int(eq1[3][2:])
        b1 = int(eq2[2][2:-1])
        b2 = int(eq2[3][2:])
        c1 = int(eq3[1][2:-1]) + 10000000000000
        c2 = int(eq3[2][2:]) + 10000000000000
        equations.append(((a1,a2),(b1,b2),(c1,c2)))
    return equations

#===============================================================================
def process_data(data):
    """Process data as needed"""
    tokens = 0
    for system in data:
        a,b,c = system
        y = ( (a[0]*c[1]) - (a[1]*c[0]) ) / \
            ( (a[0]*b[1]) - (a[1]*b[0]) )
        x = ( c[0] - (b[0] * y) ) / a[0]
        if ( x % 1 == y % 1):
            tokens += 3*int(x) + int(y)
    return tokens

#===============================================================================
if __name__ == "__main__":
    main()
