#!/usr/bin/python
from sys import argv

def main():

    if len(argv) != 2:
        print("Invalid # of arguments")
        return

    dim, lines = preprocess(argv[1])
    data = process_lines(dim, lines)
    process_data(data)

def preprocess(file):
    lines = []
    height = 0
    with open(file) as file:
        content = file.read().split('\n')
    for line in content:
        line = line.strip()
        if line:
            lines.append(line)
            height += 1
    width = len(lines[0])
    return (height, width), lines

def process_lines(dim, lines):
    left  = []
    right = {}
    for line in lines:
        l,r = line.split()
        l = int(l)
        r = int(r)
        left.append(l)
        right[l] = right.get(l,0)
        right[r] = right.get(r,0) + 1
    return (left, right)
            
def process_data(data):
    similarity = 0
    left, right = data
    for n in left:
        score = n * right[n]
        similarity += score
        print(score,'=',n,'*',right[n])
    print(similarity)

if __name__ == "__main__":
    main()
