#!/usr/bin/python
from sys import argv

def main():

    if len(argv) != 2:
        print("Invalid # of arguments")
        return

    _input = preprocess(argv[1])
    data = process_lines(_input)
    result = process_data(data)
    print(result)

def preprocess(file):
    with open(file) as file:
        content = file.read().split('\n')
    return "".join(content)

def process_lines(_input):
    data = []
    state = 0
    enabled = True
    x,y = None, None
    for c in _input:
        if state == 0:
            if c == "d":   state = 6
            elif enabled and c == "m": state = 1
            else:          state = 0
        elif state == 1:
            if c == "u":   state = 2
            else:          state = 0
        elif state == 2:
            if c == "l":   state = 3
            else:          state = 0
        elif state == 3:
            if c == "(":   state = 4
            else:          state = 0
        elif state == 4:
            if c == ",":
                if x == None:
                    state = 0
                    print(f"mul(,\t INVALID 4a")
                else:
                    state = 5
            else:
                try:
                    i = int(c)
                    x = i + (10*x if x else 0)
                except:
                    x = None
                    state = 0
                    print(f"mul({x}{c}\t INVALID 4b")
        elif state == 5:
            if c == ")":
                if y:
                    data.append((x,y))
                else:
                    print(f"mul({x},)\t INVALID 5a")
                x = None
                y = None
                state = 0
            else:
                try:
                    i = int(c)
                    y = i + (10*y if y else 0)
                except:
                    x = y = None
                    state = 0
                    print(f"mul({x},{y}{c}\t INVALID 5b")
        elif state == 6:
            if c == "o":   state = 7
            else:          state = 0
        elif state == 7:
            if c == "(":   state = 8
            elif c == "n": state = 9
            else:          state = 0
        elif state == 8:
            if c == ")":
                enabled = True
            state = 0
        elif state == 9:
            if c == "'":   state = 10
            else:          state = 0
        elif state == 10:
            if c == "t":   state = 11
            else:          state = 0
        elif state == 11:
            if c == "(":   state = 12
            else:          state = 0
        elif state == 12:
            if c == ")":
                enabled = False
            state = 0

    return data
            
def process_data(data):
    sum = 0
    for x,y in data:
        prod = x*y
        sum += prod
        print(f"mul({x},{y}) = {prod}")
    return sum

if __name__ == "__main__":
    main()
