#!/usr/bin/python
from sys import argv

def main():

    if len(argv) != 2:
        print("Invalid # of arguments")
        return

    dim, lines = preprocess(argv[1])
    result = process_data(dim, lines)
    print(result)

def preprocess(file):
    lines = []
    height = 0
    with open(file) as file:
        content = file.read().split('\n')
    for line in content:
        if line.strip():
            lines.append(line)
            height += 1
    width = len(lines[0])
    return (height, width), lines

def process_data(dim, lines):
    count = 0
    for y in range(dim[0]):
        for x in range(dim[1]):
            if lines[y][x] == "X":
                count += search("XMAS", lines, x, y, *dim)
    return count

compass = [(0,-1),(0,1),(1,-1),(1,0),(1,1),(-1,-1),(-1,0),(-1,1)]

def search(word, grid, x, y, w, h):
    if not word:
        return 0
    found = 0
    n = len(word)
    for d in compass:
        _ybound = y + (n-1) * d[0]
        _xbound = x + (n-1) * d[1]
        if _xbound < 0 or _xbound >= w or _ybound < 0 or _ybound >= h:
            continue
        _y = y + d[0]
        _x = x + d[1]
        matches = True
        for i in range(1,n):
            if word[i] != grid[_y][_x]:
                matches = False
                break
            _y += d[0]
            _x += d[1]
        if matches:
            found += 1
    return found



if __name__ == "__main__":
    main()
