#!/usr/bin/python
"""Advent of Code Solution"""

from sys import argv

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    if len(argv) != 2:
        print("Invalid # of arguments")
        return

    content = preprocess(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def preprocess(filename):
    """Extract lines from file"""
    target = []
    content = [target]
    with open(filename,encoding="utf8") as file:
        lines = file.read().split('\n')
    for line in lines:
        if not line:
            target = []
            content.append(target)
            continue
        target.append(line)
    return content

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    rules = {}
    updates = []
    for rule in content[0]:
        requirement, page = rule.split("|")
        rules[page] = rules.get(page,[]) + [requirement]
    for update in content[1]:
        updates.append(update.split(','))
    return (rules,updates)

#===============================================================================
def process_data(data):
    """Process data as needed"""
    incorrect = []
    middle = []
    rules, updates = data
    for i in range(len(updates)):
        update = updates[i]
        seen = []
        valid = True
        for j in range(len(update))[::-1]:
            page = update[j]
            for must_preceed in rules.get(page,[]):
                if must_preceed in seen:
                    fix_page(rules, update, j)
                    valid = False
            seen.append(page)
        if not valid:
            n = len(update) // 2
            middle.append(int(update[n]))
    return sum(middle)


#===============================================================================
def fix_page(rules, update, index):
    page = update.pop(index)
    must_preceed = rules[page]
    for i in range(index, len(update)):
        if update[i] in must_preceed:
            index = i+1
    update.insert(index, page)

#===============================================================================
if __name__ == "__main__":
    main()
