#!/usr/bin/python
"""Advent of Code Solution"""

from sys import argv

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    if len(argv) != 2:
        print("Invalid # of arguments")
        return
    content = preprocess(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def preprocess(filename):
    """Extract lines from file"""
    content = []
    with open(filename,encoding="utf8") as file:
        lines = file.read().split('\n')
    for line in lines:
        if line:
            content.append(line)
    return content

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    h = len(content)
    w = len(content[0])
    for y in range(h):
        for x in range(w):
            if content[y][x] not in ['.','#']:
                return (content, (y,x), (h,w))

#===============================================================================
direction = { '^':0, '>':1, 'V':2, '<':3 }
compass = [ (-1,0), (0,1), (1,0), (0,-1) ]

#===============================================================================
def process_data(data):
    """Process data as needed"""
    map = data[0]
    y,x = data[1]
    h,w = data[2]
    grid = [[0 for _x in range(w)] for _y in range(h)]
    print("Guard","=",map[y][x])
    heading = direction[map[y][x]]
    dy, dx = compass[heading]
    _y,_x = y+dy, x+dx
    grid[y][x] = 1
    while (_y >= 0) and (_x >= 0) and (_y < h) and (_x < w):
        path = map[y + dy][x + dx]
        if path == '#':
            heading = (heading+1) % 4
            dy, dx = compass[heading]
        y += dy
        x += dx
        _y,_x = y+dy, x+dx
        grid[y][x] = 1
    return sum(sum(row) for row in grid)

#===============================================================================
def print_traveled(grid, map, h, w, _y, _x):
    for y in range(h):
        for x in range(w):
            if y == _y and x == _x:
                print('▞',end='')
            elif map[y][x] == '#':
                print('#',end='')
            elif grid[y][x]:
                print('█',end='')
            else:
                print('░',end='')
        print()



#===============================================================================
if __name__ == "__main__":
    main()
