#!/usr/bin/python
"""Advent of Code Solution"""

from sys import argv

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    if len(argv) != 2:
        print("Invalid # of arguments")
        return
    content = preprocess(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def preprocess(filename):
    """Extract lines from file"""
    content = []
    with open(filename,encoding="utf8") as file:
        lines = file.read().split('\n')
    for line in lines:
        if line:
            content.append(line)
    return content

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    h = len(content)
    w = len(content[0])
    for y in range(h):
        for x in range(w):
            if content[y][x] not in ['.','#']:
                return (content, (y,x), (h,w))

#===============================================================================
direction = { '^':0, '>':1, 'V':2, '<':3 }
compass = [ (-1,0), (0,1), (1,0), (0,-1) ]

#===============================================================================
def process_data(data):
    """Process data as needed"""
    walls = [[col == '#' for col in row] for row in data[0]]
    y,x = data[1]
    h,w = data[2]
    heading = direction[data[0][y][x]]
    count, _ = traverse(walls, heading, y, x, h, w, recursive=True)
    return count


#===============================================================================
def traverse(walls,heading,y,x,h,w,recursive=False):
    """Iterate over guard path until out of bounds or loop detected"""
    count = 0
    turning = (heading+1) % 4
    start = (y,x)
    dy,dx = compass[heading]
    ty,tx = compass[turning]
    grid = [[0 for _x in range(w)] for _y in range(h)]
    grid[y][x] = heading
    _y,_x = y+dy, x+dx
    n = 0
    while not ((_y < 0) or (_x < 0) or (_y >= h) or (_x >= w)):
        n += 1

        # Turn if wall encountered
        if walls[_y][_x]:
            heading = turning
            dy,dx   = ty,tx
            turning = (turning+1) % 4
            ty,tx   = compass[turning]
            grid[y][x] |= 1 << heading

        # Check if placing an obstacle here would cause a loop
        elif recursive:
            if (_y,_x) != start:
                walls[_y][_x] = True
                _, loop = traverse(walls,turning,y,x,h,w)
                if loop:
                    count += 1
                    print(f"({(_y, _x)})")
                    #print(count,'/',n,end='\r')
                walls[_y][_x] = False

        # Default behavior
        else:
            if grid[_y][_x] & (1 << heading):
                #print_route(grid,walls,h,w,*start)
                return 0, True
        y, x  = y+dy, x+dx
        _y,_x = y+dy, x+dx
        grid[y][x] |= 1 << heading
    #if recursive:
        #print_route(grid,walls,h,w,[start,(100,116)])
    return count, False



#===============================================================================
def print_route(grid, walls, h, w, coords):
    for y in range(h):
        for x in range(w):
            vert = grid[y][x] & 0b0101
            horz = grid[y][x] & 0b1010
            if (y,x) in coords:    print('█',end='')
            elif walls[y][x]:      print('#',end='')
            elif vert and horz:    print('╬',end='')
            elif vert:             print('║',end='')
            elif horz:             print('═',end='')
            #elif grid[y][x] ==  1: print('^',end='')
            #elif grid[y][x] ==  2: print('>',end='')
            #elif grid[y][x] ==  4: print('v',end='')
            #elif grid[y][x] ==  8: print('<',end='')
            #elif grid[y][x] == 15: print('╬',end='')
            #elif grid[y][x] ==  5: print('║',end='')
            #elif grid[y][x] == 10: print('═',end='')
            #elif grid[y][x] == 12: print('╗',end='')
            #elif grid[y][x] ==  3: print('╚',end='')
            #elif grid[y][x] ==  6: print('╔',end='')
            #elif grid[y][x] ==  9: print('╝',end='')
            #elif grid[y][x] ==  7: print('╠',end='')
            #elif grid[y][x] == 13: print('╣',end='')
            #elif grid[y][x] == 14: print('╦',end='')
            #elif grid[y][x] == 11: print('╩',end='')
            else:                  print('░',end='')
        print()
    print()

#===============================================================================
if __name__ == "__main__":
    main()
