#!/usr/bin/python
"""Advent of Code Solution"""

from sys import argv

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    if len(argv) != 2:
        print("Invalid # of arguments")
        return
    content = preprocess(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def preprocess(filename):
    """Extract lines from file"""
    content = []
    with open(filename,encoding="utf8") as file:
        lines = file.read().split('\n')
    for line in lines:
        if line:
            content.append(line)
    return content

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    h,w = len(content), len(content[0])
    antinodes = [[False for x in range(w)] for y in range(h)]
    antennas = {}
    for y in range(h):
        for x in range(w):
            item = content[y][x]
            if item != '.':
                frequency = antennas.get(item,[])
                frequency.append((y,x))
                antennas[item] = frequency
    return (antinodes, antennas, (h,w))

#===============================================================================
def process_data(data):
    """Process data as needed"""
    antinodes = data[0]
    antennas  = data[1]
    h, w      = data[2]
    for freq in antennas:
        for a1 in antennas[freq]:
            for a2 in antennas[freq]:
                find_and_place_antinodes(a1,a2,antinodes,h,w)
    return sum(sum(row) for row in antinodes)

#===============================================================================
def find_and_place_antinodes(a1, a2, antinodes, h, w):
    """Finds antinode locations and places them on the grid"""
    if a1 == a2:
        return
    dy = a2[0] - a1[0]
    dx = a2[1] - a1[1]
    y1 = a2[0] + dy
    x1 = a2[1] + dx
    y2 = a1[0] - dy
    x2 = a1[1] - dx
    if not ((y1 < 0) or (x1 < 0) or (y1 >= h) or (x1 >= w)):
        antinodes[y1][x1] = 1
    if not ((y2 < 0) or (x2 < 0) or (y2 >= h) or (x2 >= w)):
        antinodes[y2][x2] = 1


#===============================================================================
if __name__ == "__main__":
    main()
