#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *
from itertools import permutations

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    content = read_lines(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
class Guest():
    def __init__(self):
        self.affinity = {}
    def mood(self, guest, happiness):
        self.affinity[guest] = happiness

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    guest_list = {}
    for line in content:
        line = line.split()
        guest = line[0]
        change = line[2]
        neighbor = line[-1][:-1]
        if change == "gain":
            amount = int(line[3])
        else:
            amount = -int(line[3])
        if guest not in guest_list:
            guest_list[guest] = Guest()
        if neighbor not in guest_list:
            guest_list[neighbor] = Guest()
        guest_list[guest].mood(guest_list[neighbor], amount)
    return guest_list

#===============================================================================
def process_data(data):
    """Process data as needed"""
    arrangements = permutations(data.values())
    optimal = score(next(arrangements))
    for arrangement in arrangements:
        happiness = score(arrangement)
        if optimal < happiness:
            optimal = happiness
    return optimal

#===============================================================================
def score(arrangement):
    happiness = 0
    head = arrangement[0]
    a = head
    for i in range(1,len(arrangement)):
        b = arrangement[i]
        happiness += a.affinity[b]
        happiness += b.affinity[a]
        a = b
    happiness += head.affinity[b]
    happiness += b.affinity[head]
    return happiness

#===============================================================================
if __name__ == "__main__":
    main()
