#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *
from itertools import permutations

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    content = read_lines(argv[1])
    data = process_lines(content)
    add_arbiter(data)
    result = process_data(data)
    print(result)

#===============================================================================
class Guest():
    def __init__(self, name):
        self.affinity = {}
        self.name = name
    def mood(self, guest, happiness):
        self.affinity[guest] = happiness

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    guest_list = {}
    for line in content:
        line = line.split()
        guest = line[0]
        change = line[2]
        neighbor = line[-1][:-1]
        if change == "gain":
            amount = int(line[3])
        else:
            amount = -int(line[3])
        if guest not in guest_list:
            guest_list[guest] = Guest(guest)
        if neighbor not in guest_list:
            guest_list[neighbor] = Guest(neighbor)
        guest_list[guest].mood(guest_list[neighbor], amount)
    return guest_list

#===============================================================================
def add_arbiter(guest_list):
    arbiter = Guest("You")
    for guest in guest_list.values():
        guest.mood(arbiter, 0)
        arbiter.mood(guest, 0)
    guest_list["You"] = arbiter

#===============================================================================
def print_table(table):
    head = table[0]
    a = head
    print('='*80)
    print(a.name)
    for i in range(1,len(table)):
        b = table[i]
        print(a.affinity[b])
        print(b.affinity[a])
        print(b.name)
        a = b
    print(b.affinity[head])
    print(head.affinity[b])
    print(head.name)

#===============================================================================
def process_data(data):
    """Process data as needed"""
    arrangement = list(permutations(data.values()))
    best_table  = arrangement[0]
    optimal = score(best_table)
    for table in arrangement[1:]:
        happiness = score(table)
        if optimal < happiness:
            optimal = happiness
            best_table = table
    return optimal

#===============================================================================
def score(arrangement):
    happiness = 0
    head = arrangement[0]
    a = head
    for i in range(1,len(arrangement)):
        b = arrangement[i]
        happiness += a.affinity[b]
        happiness += b.affinity[a]
        a = b
    happiness += head.affinity[b]
    happiness += b.affinity[head]
    return happiness

#===============================================================================
if __name__ == "__main__":
    main()
