#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *
from math import prod

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    content = read_lines(argv[1])
    data = process_lines(content)
    result = process_data(data)
    print(result)

#===============================================================================
def permutation(n, m):
    N = n+1
    for a in range(N):
        for b in range(N-a):
            for c in range(N-a-b):
                d = n-a-b-c
                yield (a,b,c,d)

#===============================================================================
def process_lines(content):
    """Parse lines into useable data"""
    ingredients = {}
    for line in content:
        line = line.split()
        properties = {}
        ingredients[line[0]] = [int(value[:-1] if value[-1] == ',' else value) for value in line[2::2]]
    return ingredients

#===============================================================================
def process_data(data):
    """Process data as needed"""
    total  = 100
    pantry = list(data.values())
    count  = len(pantry)
    props  = len(pantry[0])
    best   = 0
    for n in permutation(total,len(pantry)):
        scores = [n[0] * value for value in pantry[0]]
        for i in range(1,count):
            for j in range(props):
                scores[j] += n[i] * pantry[i][j]
        for j in range(props):
            if scores[j] < 0:
                scores[j] = 0
        if scores[-1] == 500:
            total = prod(scores[:-1])
            if best < total:
                best = total
                print(best,scores,n,pantry)
    return best
                

#===============================================================================
if __name__ == "__main__":
    main()


"""Notes

100 = w + x + y + z
s1 = a1*w + b1*x + c1*y + d1*z
s2 = a2*w + b2*x + c2*y + d2*z
s3 = a3*w + b3*x + c3*y + d3*z
s4 = a4*w + b4*x + c4*y + d4*z
S = s1 * s2 * s3 * s4
find max(S)

dS/dx = SUM(dS/dsN * dsN/dX) for N in {1..4}
dS/ds1 = s2 * s3 * s4
dS/ds2 = s1 * s3 * s4
dS/ds3 = s1 * s2 * s4
dS/ds4 = s1 * s2 * s3

ds1/dx = b1

dS/ds1 * ds1/dw = a1 * (s2 * s3 * s4)
dS/ds1 * ds1/dx = b1 * (s2 * s3 * s4)
dS/ds1 * ds1/dy = c1 * (s2 * s3 * s4)
dS/ds1 * ds1/dz = d1 * (s2 * s3 * s4)

dS/dw = a1(s2s3s4) + a2(s1s3s4) + a3(s1s2s4) + a4(s1s2s3)
dS/dx = b1(s2s3s4) + b2(s1s3s4) + b3(s1s2s4) + b4(s1s2s3)
dS/dy = c1(s2s3s4) + c2(s1s3s4) + c3(s1s2s4) + c4(s1s2s3)
dS/dz = d1(s2s3s4) + d2(s1s3s4) + d3(s1s2s4) + d4(s1s2s3)

Different Train of though: Permutations

100 0 0 0   Split up 100 and 0
99 1 0 0    Split up 99 and 1
99 0 1 0
99 0 0 1
98 2 0 0    Split up 98 and 2
98 0 2 0
98 0 0 2
98 1 1 0    SPlut up 98, 1, and 1
98 1 0 1
98 0 1 1
97 3 0 0
97 0 3 0
97 0 0 3


"""
