#!/usr/bin/python
"""Advent of Code Solution"""

from helper import *

#===============================================================================
def main():
    """Runs if script is being run as executable"""
    arg_check()
    data = read_lines(argv[1])
    result = process_data(data)
    print(result)

bad = {'a':'b', 'c':'d', 'p':'q', 'x':'y'}

#===============================================================================
def process_data(data):
    """Process data as needed"""
    nice = 0
    for line in data:
        prev = line[0]
        twice = False
        pairs = False
        seen  = {}
        for i in range(2,len(line)):
            if line[i-2] == line[i]:
                twice = True
            if line[i-1:i+1] in seen:
                pairs = True
            seen[line[i-2:i]] = True
        if twice and pairs:
            nice += 1
    return nice

#===============================================================================
if __name__ == "__main__":
    main()
